# Based on ClassiCube workflow script by UnknownShadow200, modified by Aftersol
#
# Original workflow build script: https://github.com/ClassiCube/ClassiCube/blob/master/.github/workflows/build_n64.yml
#
# Based on ClassiCube workflow script for building N64 ROM by UnknownShadow200 so here is the
# license for this script per ClassiCube licensing terms
#
#﻿ Copyright (c) 2014 - 2024, UnknownShadow200
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, 
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this 
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this 
# list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# 3. Neither the name of ClassiCube nor the names of its contributors may be 
# used to endorse or promote products derived from this software without specific prior 
# written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
# SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT 
# OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) 
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

name: Build latest N64 QOI Screenshot ROM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dragonminded/libdragon:preview
    steps:
      - uses: actions/checkout@v5
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get -y install curl
      - name: Compile N64 build
        id: build
        run: |
          REAL_DIR=`pwd`
          cd /tmp
          git clone -b preview https://github.com/DragonMinded/libdragon.git --depth=1
          cd libdragon
          make install -j 4
          make tools-install -j 4
          cd $REAL_DIR
          make -j 4
          ls

      - uses: ./.github/actions/upload-artifact
        if: ${{ always() && steps.build.outcome == 'success' }}
        with:
          SOURCE_FILE: 'qoi_enc.z64'
          DEST_NAME: 'qoi_enc.z64'
  
