name: Make on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Build Linux
      working-directory: tools
      run: make

    - name: Upload
      uses: ./.github/actions/upload-artifact
      with:
        SOURCE_FILE: tools/qoi_enc
        DEST_NAME: qoi_enc_linux

  build-macos-arm64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v5

    - name: Build MacOS ARM64
      working-directory: tools
      run: make

    - name: Upload
      uses: ./.github/actions/upload-artifact
      with:
        SOURCE_FILE: tools/qoi_enc
        DEST_NAME: qoi_enc_macos_arm64

  build-macos-x86_64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v5

    - name: Build MacOS x86_64
      working-directory: tools
      run: make CC=clang CFLAGS="-Wall -O2 -Wpedantic -arch x86_64"

    - name: Upload
      uses: ./.github/actions/upload-artifact
      with:
        SOURCE_FILE: tools/qoi_enc
        DEST_NAME: qoi_enc_macos_x86_64

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5

    - name: Build Windows
      working-directory: tools
      shell: bash
      run: make

    - name: Upload
      uses: ./.github/actions/upload-artifact
      with:
        SOURCE_FILE: tools/qoi_enc.exe
        DEST_NAME: qoi_enc_windows

  build-windows-arm64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install MinGW ARM64 cross-compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-w64-mingw32

    - name: Build Windows ARM64
      working-directory: tools
      run: make CC=aarch64-w64-mingw32-gcc TARGET=qoi_enc.exe

    - name: Upload
      uses: ./.github/actions/upload-artifact
      with:
        SOURCE_FILE: tools/qoi_enc.exe
        DEST_NAME: qoi_enc_windows_arm64
        